# Generated by Django 5.1.6 on 2025-02-18 08:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manic_app', '0003_alter_client_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='NailTechnician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+375ххххххххх'.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('specialization', models.CharField(choices=[('classic', 'Классический маникюр'), ('gel', 'Гелевое наращивание'), ('acrylic', 'Акриловое наращивание'), ('design', 'Дизайн ногтей')], default='classic', max_length=10)),
                ('experience_years', models.PositiveIntegerField(help_text='Сколько лет опыта работы')),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('work_address', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Мастер по маникюру',
                'verbose_name_plural': 'Мастера по маникюру',
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+375ххххххххх'.", regex='^\\+?1?\\d{13,14}$')]),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Manic_app.client')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Manic_app.nailtechnician')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='Manic_app.nailtechnician')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
    ]
