# Generated by Django 5.1.6 on 2025-02-25 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manic_app', '0005_alter_client_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='work_photos/')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_photos', to='Manic_app.nailtechnician')),
            ],
        ),
    ]
